export const ADD_TO_QUEUE = "ADD_TO_QUEUE";
export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
export const DELETE_FROM_QUEUE = "DELETE_FROM_QUEUE";
export const DELETE_FROM_HISTORY = "DELETE_FROM_HISTORY";
export const RESET_QUEUE_AND_HISTORY = "RESET_QUEUE_AND_HISTORY";
